#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            set +x
            echo "error: '$2' is not a Git repository"
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

download_by_hash() {
    DOWNLOAD_COMMAND="curl -Lo"
    if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
        DOWNLOAD_COMMAND="wget -O"
        if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
            set +x
            echo "error: Neither curl nor wget found"
            exit 1
        fi
    fi
    SHA256_COMMAND="sha256sum"
    if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
        SHA256_COMMAND="sha256"
        if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
            set +x
            echo "error: Cannot find sha256(sum) command"
            exit 1
        fi
    fi
    if ! test -f "$2" || ! $SHA256_COMMAND "$2" | grep $3 >/dev/null 2>&1; then
        rm -f "$2"
        mkdir -p "$2" && rm -rf "$2"
        $DOWNLOAD_COMMAND "$2" $1
        if ! $SHA256_COMMAND "$2" | grep $3 >/dev/null 2>&1; then
            set +x
            echo "error: Cannot download file '$2' by hash"
            echo "incorrect hash:"
            $SHA256_COMMAND "$2"
            rm -f "$2"
            exit 1
        fi
    fi
}

find_and_replace() {
# $1 - directory
# $2 - search string
# $3 - replace string
    find "$1" -type f -exec sed -i "s/$2/$3/g" {} +
}

clone_repo_commit \
    https://github.com/osdev0/freestnd-c-hdrs-0bsd.git \
    freestnd-c-hdrs-0bsd \
    0353851fdebe0eb6a4d2c608c5393040d310bf35

clone_repo_commit \
    https://github.com/osdev0/cc-runtime.git \
    cc-runtime \
    9c281448fe40498a6341d74f55c9af4f642c0b1d

download_by_hash \
    https://github.com/limine-bootloader/limine/raw/7cddb61183685d9bddd2eb13d42223d929c2abe6/limine.h \
    src/limine.h \
    c00e7d4cd6e2674eca481f978b64a7fb8c8479cc32c466ec35aad2207761bf01

clone_repo_commit \
    https://codeberg.org/r4/smoldtb.git \
    src/dtb/smoldtb \
    f61e7dbec93e64ac9abfaf09a7b3b706fe06f0c1

# special for dtb
rm -f src/dtb/smoldtb/test.c

clone_repo_commit \
    https://github.com/mintsuki/flanterm \
    src/flanterm \
    6f4e92ed8f7202bda3a53e28fd527f2f997bbb5c

find_and_replace src/dtb/smoldtb/smoldtb.h "dtb_init" "smoldtb_init"
find_and_replace src/dtb/smoldtb/smoldtb.c "dtb_init" "smoldtb_init"
