#pragma once

#define RAM_START 0x80000000
#define MAXVA (1L << (9 + 9 + 9 + 12 - 1))
#define TRAMPOLINE (MAXVA - 4096)
#define KSTACK_GUARD_PAGES 1
#define KSTACK_PAGES 16
#define KSTACK_STRIDE ((KSTACK_GUARD_PAGES + KSTACK_PAGES) * 4096)
#define KSTACK(p) (TRAMPOLINE - ((p) + 1) * KSTACK_STRIDE)
#define TRAPFRAME (TRAMPOLINE - 4096)
